package net.pkhapps.idispatchx.gis.server.model;

import java.util.Objects;
import java.util.Set;

/**
 * Represents a WMTS tile layer with metadata about available zoom levels.
 * <p>
 * A tile layer has a name and a set of zoom levels for which pre-rendered tiles
 * are available. Tiles at other zoom levels must be generated by resampling from
 * the nearest available zoom level.
 *
 * @param name                the layer name (must not be blank)
 * @param availableZoomLevels the set of zoom levels with pre-rendered tiles
 */
public record TileLayer(String name, Set<Integer> availableZoomLevels) {

    /**
     * Creates a new tile layer with validation.
     *
     * @param name                the layer name
     * @param availableZoomLevels the set of zoom levels with pre-rendered tiles
     * @throws NullPointerException     if name or availableZoomLevels is null
     * @throws IllegalArgumentException if name is blank
     * @throws IllegalArgumentException if any zoom level is outside the valid range 0-15
     */
    public TileLayer {
        Objects.requireNonNull(name, "name must not be null");
        Objects.requireNonNull(availableZoomLevels, "availableZoomLevels must not be null");

        if (name.isBlank()) {
            throw new IllegalArgumentException("name must not be blank");
        }

        for (var zoomLevel : availableZoomLevels) {
            if (zoomLevel < TileCoordinates.MIN_ZOOM || zoomLevel > TileCoordinates.MAX_ZOOM) {
                throw new IllegalArgumentException(
                        "zoom level must be between " + TileCoordinates.MIN_ZOOM +
                                " and " + TileCoordinates.MAX_ZOOM + ", got " + zoomLevel);
            }
        }

        // Make defensive copy to ensure immutability
        availableZoomLevels = Set.copyOf(availableZoomLevels);
    }

    /**
     * Checks if this layer has pre-rendered tiles at the specified zoom level.
     *
     * @param zoom the zoom level to check
     * @return true if tiles are available at this zoom level, false otherwise
     */
    public boolean hasZoomLevel(int zoom) {
        return availableZoomLevels.contains(zoom);
    }

    /**
     * Returns the nearest available zoom level that is less than or equal to
     * the requested zoom level.
     * <p>
     * This is useful for determining which pre-rendered tiles to use as the
     * source for resampling when tiles at the requested zoom level are not
     * available.
     *
     * @param requestedZoom the requested zoom level
     * @return the nearest available lower zoom level, or -1 if no lower zoom level is available
     */
    public int nearestAvailableZoom(int requestedZoom) {
        var nearest = -1;
        for (var available : availableZoomLevels) {
            if (available <= requestedZoom && available > nearest) {
                nearest = available;
            }
        }
        return nearest;
    }
}
